name: Api-Gateway

on:
  push:
    paths:
      - api-gateway/**
    branches:
      - '**'

jobs:
  build:
    name: Build Api-Gateway Service
    runs-on: ubuntu-latest
    env:
      working-directory: ./api-gateway
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: 'maven'

      - name: Set execute permission for mvnw
        run: chmod +x ./mvnw

      - name: Build with maven
        run: ./mvnw -ntp verify

      - if: ${{ github.ref == 'refs/heads/main'}}
        name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - if: ${{ github.ref == 'refs/heads/main'}}
        name: Build and Publish Docker Image
        run: |
          ./mvnw spring-boot:build-image -DskipTests
          docker push ${{ secrets.DOCKER_HUB_USERNAME}}/bookstore-api-gateway
